channels:
  - conda-forge
dependencies:
  - python>=3.7
  - numpy>=1.15
  - scipy>=1.5
  - numba>=0.51
  - pandas>=0.20.0
  - flake8>=3.7.7
  - flake8-docstrings>=1.5.0
  - black>=19.5b0
  - pytest-cov>=2.10.0
  - dask>=1.2.2
  - distributed>=1.28.1
  - jupyterlab>=3.0
  - matplotlib>=3.3.0
  - lxml>=4.5.2
  - twine>=3.2.0
  - sphinx>=3.5.3
  - nbsphinx>=0.8.1
  - pydata-sphinx-theme>=0.5.2
  - scikit-learn>=0.21.3
  - numpydoc>=1.1.0
  - build>=0.7.0
